import pandas as pd, numpy as np 
df = pd.read_csv('data/clean_search_dataset.csv')


# qid,pid,query_clean,passage_clean,relevance
# 188714,1000052,foods and supplements to lower blood sugar,watch portion sizes even healthy foods will cause high blood sugar if you eat too much make sure each of your meals has the same amount of chos avoid foods high in sugar some foods to avoid sugar honey candies syrup cakes cookies regular soda and,0
# 1082792,1000084,what does the golgi apparatus do to the proteins and lipids once they arrive,start studying bonding carbs proteins lipids learn vocabulary terms and more with flashcards games and other study tools,0
# 995526,1000094,where is the federal penitentiary in ind,it takes thousands of macys associates to bring the magic of macys to life our associate team is an invaluable part of who we are and what we do f ind the seasonal job thats right for you at holidaymacysjobscom,0
# 199776,1000115,health benefits of eating vegetarian,the good news is that you will discover what goes into action spurs narrowing of these foods not only a theoretical supposition there are diagnosed with great remedy is said that most people and more can be done duncan was a wonderful can eating chicken cause gout benefits of natural options with your health,0
# 660957,1000115,what foods are good if you have gout,the good news is that you will discover what goes into action spurs narrowing of these foods not only a theoretical supposition there are diagnosed with great remedy is said that most people and more can be done duncan was a wonderful can eating chicken cause gout benefits of natural options with your health,0
# 820267,1000130,what is the endocrine system responsible for,the pancreas secretes pancreatic enzyme which is responsible for the breakdown of protein but it also secretes insulin so that we can get energy from glucose making it a part of the endocrine system or glands the liver detoxifies all of the blood that carries absorbed nutrients from the digestive system,0
# 837202,1000252,what is the nutritional value of oatmeal,oats make an easy balanced breakfast one cup of cooked oatmeal contains about 150 calories four grams of fiber about half soluble and half insoluble and six grams of protein to boost protein further my favorite way to eat oatmeal is with a swirl of almond butter nestled within,0
# 130825,1000268,definition for daring,such a requirement would have three desirable consequences first it would tend to make bank executives more conservative and less daring in gambling with other peoples money second it would put this liability of financial decision makers ahead of any taxpayer bailout in case of insolvency and third it would create a potentially powerful diseconomy of scale within big conglomerate banks,0
# 408149,1000288,is dhgate a scam,if you think you ve been targeted by a counterfeit check scam report it to the following agencies 1 the federal trade commission or 1877ftchelp 18773824357 2 the us postal inspection service or call your local post office 3 the number is in the blue pages of your local telephone directoryere s how to avoid a counterfeit check scam 1 throw away any offer that asks you to pay for a prize or a gift 2 if it s free or a gift a promotion or a sweepstakes you shouldn t have to pay anything for it,0
# 345453,1000327,how to become a teacher assistant,top 10 amazing movie makeup transformations biological chemistry or biochemistry is the study of the chemical composition of living organisms at a cellular levelomeone seeking a career in biological chemistry will usually need at least a bachelors degree with a bachelors degree an individual can qualify for a job as a science teacher at the high school level a research assistant laboratory technician or a scientist in a testing environment,0
